
export const ADD_TO_CARD = 'ADD_TO_CARD';
export const DELETE_FROM_CARD = 'DELETE_FROM_CARD';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';

export const FIND_EMPLOYEE = 'FIND_EMPLOYEE';
export const FIND_CUSTOMER = 'FIND_CUSTOMER';
